# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/iap_project/iap_project.srcs/sources_1/ip/pause_map/pause_map.xci
# IP: The module: 'pause_map' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/iap_project/iap_project.srcs/sources_1/ip/pause_map/pause_map_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pause_map'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: Z:/iap_project/iap_project.srcs/sources_1/ip/pause_map/pause_map.xci
# IP: The module: 'pause_map' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/iap_project/iap_project.srcs/sources_1/ip/pause_map/pause_map_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pause_map'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
