# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/nexys4_ddr_default.xdc

# IP: ip/gameover_rom/gameover_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gameover_rom || ORIG_REF_NAME==gameover_rom} -quiet] -quiet

# IP: ip/banner_rom/banner_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==banner_rom || ORIG_REF_NAME==banner_rom} -quiet] -quiet
