# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Z:/Labs/iap_project/iap_project.cache/wt [current_project]
set_property parent.project_path Z:/Labs/iap_project/iap_project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo z:/Labs/iap_project/iap_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files Z:/Labs/ROMs/galagaLogo_image.coe
add_files Z:/Labs/ROMs/galagaLogo_color_map_red.coe
add_files Z:/Labs/ROMs/galagaLogo_color_map_green.coe
add_files Z:/Labs/ROMs/galagaLogo_color_map_blue.coe
add_files Z:/Labs/ROMs/startInstructions_image.coe
add_files Z:/Labs/ROMs/grey_color_map.coe
add_files Z:/Labs/ROMs/buttonFuncs_image.coe
add_files Z:/Labs/ROMs/pauseScreen_image.coe
add_files Z:/Labs/ROMs/gameoverLogo_image.coe
add_files Z:/Labs/ROMs/gameoverLogo_color_map_red.coe
add_files Z:/Labs/ROMs/gameoverLogo_color_map_green.coe
add_files Z:/Labs/ROMs/gameoverLogo_color_map_blue.coe
read_verilog -library xil_defaultlib -sv {
  Z:/Labs/iap_project/iap_project.srcs/sources_1/new/gameplay.sv
  Z:/Labs/iap_project/iap_project.srcs/sources_1/new/sprite_building.sv
  Z:/Labs/iap_project/iap_project.srcs/sources_1/new/support.sv
  Z:/Labs/iap_project/iap_project.srcs/sources_1/new/top_level.sv
}
read_ip -quiet Z:/Labs/iap_project/iap_project.srcs/sources_1/ip/banner_blue/banner_blue.xci
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/banner_blue/banner_blue_ooc.xdc]

read_ip -quiet Z:/Labs/iap_project/iap_project.srcs/sources_1/ip/banner_rom/banner_rom.xci
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/banner_rom/banner_rom_ooc.xdc]

read_ip -quiet Z:/Labs/iap_project/iap_project.srcs/sources_1/ip/banner_red/banner_red.xci
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/banner_red/banner_red_ooc.xdc]

read_ip -quiet Z:/Labs/iap_project/iap_project.srcs/sources_1/ip/banner_green/banner_green.xci
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/banner_green/banner_green_ooc.xdc]

read_ip -quiet Z:/Labs/iap_project/iap_project.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc]

read_ip -quiet Z:/Labs/iap_project/iap_project.srcs/sources_1/ip/instructions_rom/instructions_rom.xci
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/instructions_rom/instructions_rom_ooc.xdc]

read_ip -quiet Z:/Labs/iap_project/iap_project.srcs/sources_1/ip/grey_map/grey_map.xci
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/grey_map/grey_map_ooc.xdc]

read_ip -quiet Z:/Labs/iap_project/iap_project.srcs/sources_1/ip/buttons_rom/buttons_rom.xci
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/buttons_rom/buttons_rom_ooc.xdc]

read_ip -quiet Z:/Labs/iap_project/iap_project.srcs/sources_1/ip/pause_rom/pause_rom.xci
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/pause_rom/pause_rom_ooc.xdc]

read_ip -quiet Z:/Labs/iap_project/iap_project.srcs/sources_1/ip/gameover_rom/gameover_rom.xci
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/gameover_rom/gameover_rom_ooc.xdc]

read_ip -quiet Z:/Labs/iap_project/iap_project.srcs/sources_1/ip/gameover_red/gameover_red.xci
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/gameover_red/gameover_red_ooc.xdc]

read_ip -quiet Z:/Labs/iap_project/iap_project.srcs/sources_1/ip/gameover_green/gameover_green.xci
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/gameover_green/gameover_green_ooc.xdc]

read_ip -quiet Z:/Labs/iap_project/iap_project.srcs/sources_1/ip/gameover_blue/gameover_blue.xci
set_property used_in_implementation false [get_files -all z:/Labs/iap_project/iap_project.srcs/sources_1/ip/gameover_blue/gameover_blue_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc Z:/Labs/iap_project/iap_project.srcs/constrs_1/imports/nexys4_ddr_default.xdc
set_property used_in_implementation false [get_files Z:/Labs/iap_project/iap_project.srcs/constrs_1/imports/nexys4_ddr_default.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_level -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
