# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/iap_project/iap_project.srcs/sources_1/ip/instructions_map/instructions_map.xci
# IP: The module: 'instructions_map' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/iap_project/iap_project.srcs/sources_1/ip/instructions_map/instructions_map_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instructions_map'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: Z:/iap_project/iap_project.srcs/sources_1/ip/instructions_map/instructions_map.xci
# IP: The module: 'instructions_map' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/iap_project/iap_project.srcs/sources_1/ip/instructions_map/instructions_map_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instructions_map'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
