# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/iap_project/iap_project.srcs/sources_1/ip/gameover_green/gameover_green.xci
# IP: The module: 'gameover_green' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/iap_project/iap_project.srcs/sources_1/ip/gameover_green/gameover_green_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gameover_green'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: z:/iap_project/iap_project.srcs/sources_1/ip/gameover_green/gameover_green.xci
# IP: The module: 'gameover_green' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/iap_project/iap_project.srcs/sources_1/ip/gameover_green/gameover_green_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gameover_green'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
